develop
dkepamprotonme/Expressions.Task3.QueryProvider pull request #1
Opened 2022-11-10 07:37 UTC by dkepamprotonme

2022-11-24 19:09 UTC, Ungerfall requested changes
Tests are red
> ========== Test run finished: 11 Tests (2 Passed, 6 Failed, 3 Skipped) run in 665 ms ==========

2022-11-24 19:18 UTC, Ungerfall commented on Expressions.Task3.E3SQueryProvider/ExpressionToFTSRequestTranslator.cs
> +                && (node.Method.Name == "Equals"
upgrade to `nameof`

2022-11-25 09:59 UTC, Ungerfall approved these changes

2022-11-25 10:03 UTC, dkepamprotonme commented on Expressions.Task3.E3SQueryProvider/ExpressionToFTSRequestTranslator.cs
> +                && (node.Method.Name == "Equals"
I have changed

2022-11-25 10:08 UTC, Ungerfall approved these changes

2022-11-25 10:08 UTC, merged